"""models.py 수정

Revision ID: 031912db2a9c
Revises: 63d79ca021bd
Create Date: 2025-05-26 00:55:05.487096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '031912db2a9c'
down_revision: Union[str, None] = '63d79ca021bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_questions', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.drop_column('student_questions', 'created_at')
    op.drop_column('student_questions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_questions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('student_questions', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
