"""models.py 수정

Revision ID: 1272ab5d8584
Revises: 9b30d14adddf
Create Date: 2025-05-26 23:58:56.262824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1272ab5d8584'
down_revision: Union[str, None] = '9b30d14adddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_snapshots',
    sa.Column('is_image', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_snapshots', 'is_image')
    # ### end Alembic commands ###
