"""add assistant_thread_id to user

Revision ID: 136bfe807e7a
Revises: 936ae45a45f1
Create Date: 2025-04-10 22:02:41.852299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136bfe807e7a'
down_revision: Union[str, None] = '936ae45a45f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assistant_thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assistant_thread_id')
    # ### end Alembic commands ###
