"""models.py 수정

Revision ID: 2254ed79366c
Revises: 19af06efb7da
Create Date: 2025-05-16 19:06:07.641388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2254ed79366c'
down_revision: Union[str, None] = '19af06efb7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_summaries', sa.Column('image_text_1', sa.Text(), nullable=True))
    op.add_column('lecture_summaries', sa.Column('image_text_2', sa.Text(), nullable=True))
    op.add_column('lecture_summaries', sa.Column('image_text_3', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_summaries', 'image_text_3')
    op.drop_column('lecture_summaries', 'image_text_2')
    op.drop_column('lecture_summaries', 'image_text_1')
    # ### end Alembic commands ###
