"""ThreadMessage  추가

Revision ID: 33a94e9b4e28
Revises: 699ba0b63314
Create Date: 2025-05-11 17:23:41.867659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a94e9b4e28'
down_revision: Union[str, None] = '699ba0b63314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thread_messages_id', table_name='thread_messages')
    op.drop_table('thread_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='thread_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thread_messages_pkey')
    )
    op.create_index('ix_thread_messages_id', 'thread_messages', ['id'], unique=False)
    # ### end Alembic commands ###
