"""initial schema

Revision ID: 418d9c2891b7
Revises: e1bfd7d1abb9
Create Date: 2025-05-07 00:53:52.646376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418d9c2891b7'
down_revision: Union[str, None] = 'e1bfd7d1abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lectures', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('lectures', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lectures', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('lectures', 'created_at')
    # ### end Alembic commands ###
