"""models.py 수정

Revision ID: 63d79ca021bd
Revises: 0538cb18d017
Create Date: 2025-05-23 22:36:35.347805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d79ca021bd'
down_revision: Union[str, None] = '0538cb18d017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_snapshots', sa.Column('summary_text', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecture_snapshots', 'summary_text')
    # ### end Alembic commands ###
