"""lecture_summary table 추가

Revision ID: 699ba0b63314
Revises: d1894edf42fc
Create Date: 2025-05-08 21:18:35.676957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699ba0b63314'
down_revision: Union[str, None] = 'd1894edf42fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('image_url_1', sa.String(), nullable=True),
    sa.Column('image_url_2', sa.String(), nullable=True),
    sa.Column('image_url_3', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_summaries_id'), 'lecture_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecture_summaries_id'), table_name='lecture_summaries')
    op.drop_table('lecture_summaries')
    # ### end Alembic commands ###
