"""Create initial tables

Revision ID: 741a2a72ac1b
Revises: 
Create Date: 2025-04-26 21:13:38.037018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741a2a72ac1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('attached_file_path', sa.String(), nullable=True))
    op.drop_constraint('chat_history_user_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_user_id_fkey', 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('assignments', 'attached_file_path')
    op.drop_column('assignments', 'deadline')
    # ### end Alembic commands ###
