"""Created or modified tables

Revision ID: 7c81b2ea478c
Revises: 
Create Date: 2025-03-25 22:09:05.121871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c81b2ea478c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['pdf_summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_id'), 'embedding', ['id'], unique=False)
    op.drop_index('ix_question_answers_id', table_name='chat_history')
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.alter_column('pdf_summary', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_lecture_materials_filename', table_name='pdf_summary')
    op.drop_index('ix_lecture_materials_id', table_name='pdf_summary')
    op.create_index(op.f('ix_pdf_summary_filename'), 'pdf_summary', ['filename'], unique=True)
    op.create_index(op.f('ix_pdf_summary_id'), 'pdf_summary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_summary_id'), table_name='pdf_summary')
    op.drop_index(op.f('ix_pdf_summary_filename'), table_name='pdf_summary')
    op.create_index('ix_lecture_materials_id', 'pdf_summary', ['id'], unique=False)
    op.create_index('ix_lecture_materials_filename', 'pdf_summary', ['filename'], unique=True)
    op.alter_column('pdf_summary', 'embedding',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.create_index('ix_question_answers_id', 'chat_history', ['id'], unique=False)
    op.drop_index(op.f('ix_embedding_id'), table_name='embedding')
    op.drop_table('embedding')
    # ### end Alembic commands ###
