"""models.py 수정

Revision ID: 9b30d14adddf
Revises: e3ffb2de636a
Create Date: 2025-05-26 01:25:49.279348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b30d14adddf'
down_revision: Union[str, None] = 'e3ffb2de636a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecture_snapshots', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.add_column('student_questions', sa.Column('q_id', sa.Integer(), nullable=False))
    op.add_column('student_questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_student_questions_id'), 'student_questions', ['id'], unique=False)
    op.create_foreign_key(None, 'student_questions', 'generated_questions', ['q_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_questions', type_='foreignkey')
    op.drop_index(op.f('ix_student_questions_id'), table_name='student_questions')
    op.drop_column('student_questions', 'created_at')
    op.drop_column('student_questions', 'q_id')
    op.alter_column('lecture_snapshots', 'summary_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
