"""re-init

Revision ID: a5129f89fc5f
Revises: 7c81b2ea478c
Create Date: 2025-03-31 20:30:41.802897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5129f89fc5f'
down_revision: Union[str, None] = '7c81b2ea478c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_snapshots_id'), 'lecture_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_lecture_snapshots_lecture_id'), 'lecture_snapshots', ['lecture_id'], unique=False)
    op.create_table('students',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_name'], ['students.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_lecture_snapshots_lecture_id'), table_name='lecture_snapshots')
    op.drop_index(op.f('ix_lecture_snapshots_id'), table_name='lecture_snapshots')
    op.drop_table('lecture_snapshots')
    # ### end Alembic commands ###
