"""Create initial tables

Revision ID: a8fa4031679a
Revises: 64b0d6e46667
Create Date: 2025-04-27 23:14:24.680051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fa4031679a'
down_revision: Union[str, None] = '64b0d6e46667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_snapshots', sa.Column('date', sa.String(), nullable=False))
    op.add_column('lecture_snapshots', sa.Column('time', sa.String(), nullable=False))
    op.add_column('lecture_snapshots', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('lecture_snapshots', sa.Column('image_path', sa.String(), nullable=False))
    op.drop_constraint('lecture_snapshots_lecture_id_fkey', 'lecture_snapshots', type_='foreignkey')
    op.drop_column('lecture_snapshots', 'timestamp')
    op.drop_column('lecture_snapshots', 'transcript')
    op.drop_column('lecture_snapshots', 'image_url')
    op.drop_column('lecture_snapshots', 'lecture_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_snapshots', sa.Column('lecture_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lecture_snapshots', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lecture_snapshots', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lecture_snapshots', sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('lecture_snapshots_lecture_id_fkey', 'lecture_snapshots', 'lectures', ['lecture_id'], ['id'])
    op.drop_column('lecture_snapshots', 'image_path')
    op.drop_column('lecture_snapshots', 'text')
    op.drop_column('lecture_snapshots', 'time')
    op.drop_column('lecture_snapshots', 'date')
    # ### end Alembic commands ###
