"""Create initial tables

Revision ID: d68da8e15418
Revises: a8fa4031679a
Create Date: 2025-04-27 23:38:05.864579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68da8e15418'
down_revision: Union[str, None] = 'a8fa4031679a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture_snapshots', sa.Column('lecture_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lecture_snapshots', 'lectures', ['lecture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lecture_snapshots', type_='foreignkey')
    op.drop_column('lecture_snapshots', 'lecture_id')
    # ### end Alembic commands ###
