"""models.py 수정

Revision ID: eb36bf178846
Revises: 33a94e9b4e28
Create Date: 2025-05-14 20:27:04.572984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb36bf178846'
down_revision: Union[str, None] = '33a94e9b4e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_questions_id', table_name='assignment_questions')
    op.drop_table('assignment_questions')
    op.drop_index('ix_assignment_threads_id', table_name='assignment_threads')
    op.drop_table('assignment_threads')
    op.drop_index('ix_thread_messages_id', table_name='thread_messages')
    op.drop_table('thread_messages')
    op.drop_column('assignment_submissions', 'assistant_thread_id')
    op.drop_column('users', 'assistant_thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('assistant_thread_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assignment_submissions', sa.Column('assistant_thread_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('thread_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='thread_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thread_messages_pkey')
    )
    op.create_index('ix_thread_messages_id', 'thread_messages', ['id'], unique=False)
    op.create_table('assignment_threads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='assignment_threads_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='assignment_threads_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignment_threads_pkey')
    )
    op.create_index('ix_assignment_threads_id', 'assignment_threads', ['id'], unique=False)
    op.create_table('assignment_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gpt_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='assignment_questions_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='assignment_questions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignment_questions_pkey')
    )
    op.create_index('ix_assignment_questions_id', 'assignment_questions', ['id'], unique=False)
    # ### end Alembic commands ###
