"""Update user model and remove student

Revision ID: fa2867e99fce
Revises: 5f1fd817d0b4
Create Date: 2025-04-01 09:33:57.877587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2867e99fce'
down_revision: Union[str, None] = '5f1fd817d0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_foreign_key(None, 'recordings', 'lectures', ['lecture_id'], ['id'])
    op.create_foreign_key(None, 'snapshots', 'lectures', ['lecture_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    # ### end Alembic commands ###
