"""models.py 수정

Revision ID: fb0110b79723
Revises: 6be8d75a1ae7
Create Date: 2025-05-21 21:16:33.958018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0110b79723'
down_revision: Union[str, None] = '6be8d75a1ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('professor_feedback', sa.Text(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('professor_feedback_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'professor_feedback_created_at')
    op.drop_column('assignment_submissions', 'professor_feedback')
    # ### end Alembic commands ###
